name: run main.py workflow

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * 1'

jobs:
  run_workflow:
    runs-on: windows-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m pip install jupyter nbconvert nbformat scrapingant-client

      - name: set pythonpath
        run: |
          echo "PYTHONPATH=D:\a\house_price_prediction\house_price_prediction\src" >> $GITHUB_ENV

      - name: run src/main.py
        env:
          GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
        run: |
          new-item  "D:\a\house_price_prediction\house_price_prediction\data\raw" -itemtype directory
          new-item  "D:\a\house_price_prediction\house_price_prediction\data\interim" -itemtype directory
          new-item  "D:\a\house_price_prediction\house_price_prediction\data\processed" -itemtype directory
          new-item  "D:\a\house_price_prediction\house_price_prediction\data\external" -itemtype directory

          new-item  "D:\a\house_price_prediction\house_price_prediction\data\raw\make_dataset_error.log" -itemtype file
          new-item  "D:\a\house_price_prediction\house_price_prediction\data\interim\build_features_error.log" -itemtype file

          python src/main.py
