name: run main.py workflow

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * 1'

jobs:
  run_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.12'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m pip install jupyter nbconvert nbformat scrapingant-client

      - name: set pythonpath
        run: |
          echo "PYTHONPATH=/home/runner/work/house_price_prediction/house_price_prediction/src" >> $GITHUB_ENV

      - name: create files and directories
        run: |
          echo mkdir -p ${{ github.workspace }}/data/raw
          echo mkdir -p ${{ github.workspace }}/data/interim
          echo mkdir -p ${{ github.workspace }}/data/processed
          echo mkdir -p ${{ github.workspace }}/data/external
          echo mkdir -p ${{ github.workspace }}/data/raw/make_dataset_error.log
          echo mkdir -p ${{ github.workspace }}/data/interim/build_features_error.log

      - name: run src/main.py
        env:
          GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
        run:
          echo mkdir -p ${{ github.workspace }}/data/raw/make_dataset_error.log
          echo mkdir -p ${{ github.workspace }}/data/interim/build_features_error.log
          python src/main.py
