name: run main.py workflow

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 1 1-12 *'

jobs:
  run_workflow:
    runs-on: ubuntu-latest

    permissions:
        contents: write
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m pip install jupyter nbconvert nbformat scrapingant-client

      - name: set pythonpath
        run: |
          echo "PYTHONPATH=/home/runner/work/house_price_prediction/house_price_prediction/src" >> $GITHUB_ENV

      - name: run src/main.py
        env:
          GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
        run: |
          python src/main.py

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v5
